version: "3"

services:
  enigma:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      MONGODB_HOST: mongodb://mongodb/enigma
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f http://localhost:8000/ping"]
      interval: 20s
      timeout: 5s
      retries: 12
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./.temp/database:/data/db
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f http://localhost:27017"]
      interval: 10s
      timeout: 5s
      retries: 12
