version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      MONGODB_HOST: mongodb://mongodb/cosmos
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./.temp/database:/data/db
